trigger:
  batch: true
  branches:
    include:
    - master
    - ?.?*  # matches to backport branches, e.g. 3.6
  tags:
    exclude:
    - '*'
pr:
  autoCancel: true
  branches:
    include:
    - master
    - ?.?*  # matches to backport branches, e.g. 3.6

stages:
- template: stage-aarch64-test.yml
- template: stage-lint.yml
- template: stage-test.yml
