stages:
- stage: azure_linux_test
  displayName: 'azure-test-aarch64'

  jobs:
  - job: 'arm64'
    strategy:
      matrix:
        Py35-C-Linux:
          python.version: '3.5'
          no_extensions: ''
          image: 'ubuntu-latest'
        Py36-C-Linux:
          python.version: '3.6'
          no_extensions: ''
          image: 'ubuntu-latest'
        Py37-C-Linux:
          python.version: '3.7'
          no_extensions: ''
          image: 'ubuntu-latest'
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - checkout: self
      submodules: true
      clean: true
      
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'  
      
    - script: docker run --rm --privileged hypriot/qemu-register
      displayName: 'Regietering qemu'
    - script: |
        export DOCKER_IMAGE=quay.io/pypa/manylinux2014_aarch64
        #bash .azure-pipelines/run_docker_build.sh '$(python.version)'
        bash -c "docker run ${DOCKER_RUN_ARGS} \
           -v "${MULTIDICT_ROOT}":/home/multidict_root:rw,z \
           -e TEST_START_INDEX \
           -e TEST_COUNT \
           -e HOST_USER_ID \
           -e CI \
           $DOCKER_IMAGE \
           bash /home/multidict_root/.azure-pipelines/build_steps.sh '$(python.version)"
      displayName: 'Running AArch64 build'
